server:
  port: 1997
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://95.179.159.62:3306/shop

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
